### ISSUE TITLE
Clone Instructions Point to a Different Repo

### ISSUE THREAD

**Issue by mjabali** [TwilioDevEd/twiliochat-node#1]
The git clone instructions provided in the README.md file point to an incorrect github repo 

First clone this repository and cd into its directory:

$ git clone git@github.com:TwilioDevEd/browser-calls-node.git

where it should be:

$ git clone git@github.com:TwilioDevEd/twiliochat-node.git

**Comment by acamino** [comment]
@mjabali thank you for this catch.
