### ISSUE TITLE
Need to Load Variables Into the Environment

### ISSUE THREAD

**Issue by mjabali** [TwilioDevEd/twiliochat-node#2]
Once you have edited the .env file, if you are using a UNIX operating system, just use the source command to load the variables into your environment otherwise an exception will happen when using the /token service.

$ source .env

If you are using a different operating system, make sure that all the variables from the .env file are loaded into your environment.

**Comment by dprothero** [comment]
Should the dotenv package be used to load the settings from the .env file?

**Comment by timothyleung** [comment]
I fixed it by adding 
```
var dotenv = require('dotenv');
dotenv.load()
```

**Comment by mcelicalderon** [comment]
Fixed! 😄
