### ISSUE TITLE
deprecated client initialization 

### ISSUE THREAD

**Issue by gatimus** [TwilioDevEd/twiliochat-node#20]
The client is initialized like:

https://github.com/TwilioDevEd/twiliochat-node/blob/b0769341ce50f4d38075ac342e7641d280474a1b/public/js/twiliochat.js#L100-L108

but if you try the same thing in TypeScript like so:

    import { Client } from 'twilio-chat';
    
    const client: Client = new Client(token);
    client.initialize().then(function() {
      // setup
    });

you get

> Constructor of class 'Client' is private and only accessible within the class declaration.

and 

> Property 'initialize' is private and only accessible within class 'Client'.

Then in the change log for [v2](https://www.twilio.com/docs/chat/javascript/changelog#programmable-chat-200-december-1-2017) it says:

> Removed deprecated Client constructor and Client.initialize function, the correct way now is to use static function Client.create.

and the current docs [here](http://media.twiliocdn.com/sdk/js/chat/releases/3.0.2/docs/index.html) and [here](https://www.twilio.com/docs/chat/initializing-sdk-clients#javascript_1) show:

    Twilio.Chat.Client.create(token).then(client => {
      // Use client
    });

This also seems to be in TwilioDevEd/twiliochat-csharp and I don't know if other tutorial repos

https://github.com/TwilioDevEd/twiliochat-csharp/blob/05cfc1bb7a09cd2870c13fc627cd45b52aa93c44/TwilioChat.Web/Scripts/lib/twiliochat.js#L94-L102

**Comment by jefflinwood** [comment]
Hi,

Thanks for bringing this to our attention! This has been fixed with this pull request. https://github.com/TwilioDevEd/twiliochat-node/pull/21

Thanks again!
